### PR TITLE
#57-feat(frontend): Laying Groundwork for Front End Concept

### PR DESCRIPTION
**Pull request by XavierGuertin**
### Summary
This PR introduces a new map component using OpenLayers to visualize wildfire data. The map includes various controls for zooming, panning, and toggling fullscreen mode.

### Changes Made
- Added `MapView` component using OpenLayers for map rendering.
- Integrated `Toolbar` component for map controls (zoom, pan, reset view, fullscreen).
- Updated `Navbar` to include a button for toggling the `Sidebar`.
- Implemented `Sidebar` component to manage map layers and datasets.
- `Sidebar` and `Toolbar` are draggable.
- Created a logo for wildfire project
- Added icons to the navbar

### Testing Instructions
1. Start the application using `npm start`.
2. Navigate to the main page.
3. Verify that the map is displayed correctly with the initial view centered at Ottawa.
4. Use the toolbar to zoom in, zoom out, reset the view, and pan the map in different directions.
5. Toggle fullscreen mode using the toolbar button.
6. Open the sidebar using the layers button in the navbar

### Screenshots (if applicable)
image

### Additional Notes
The map was made using OpenLayers for rendering and managing map layers.

### CODE REVIEW

**Review by GetGabed — APPROVED** [review]
Amazing work! Just comment open to discussion. Shouldn't we use a library for the icons? (filter, location, etc.) That way we have a more consistent design

**Comment by XavierGuertin** [comment]
> Amazing work! Just comment open to discussion. Shouldn't we use a library for the icons? (filter, location, etc.) That way we have a more consistent design

yes good point. We can implement that next. We will merge this first to allow everyone to start working on the UI.

**Review by PFratt — APPROVED** [review]
This is a fantastic base to continue building the frontend on. Another point to discuss with the team, we may not need the zoom and pan controls since OpenLayers handles those actions with the mouse. Either way, great work!

**Comment by XavierGuertin** [comment]
> This is a fantastic base to continue building the frontend on. Another point to discuss with the team, we may not need the zoom and pan controls since OpenLayers handles those actions with the mouse. Either way, great work!

yes 100%, we could only keep the fullscreen button in the right bottom corner with an icon instead

**Pull request merged**
