### PR TITLE
#39 - feat(unit-test): updated dependencies and created sample test for jest tests

### PR DESCRIPTION
**Pull request by GetGabed**
# Unit tests PR

This PR has been created to set up **unit tests in NextJS and Spring boot** in NX. 

---

## **Summary**
This PR introduces the following changes:
- Added unit tests for the **frontend** (React/Next.js) using Jest and **backend** (SpringBoot) using Java.
- Set up NX to discover the unit tests and assert their result.

---

## **Changes Made**
- Added `.babelrc` for the Jest unit tests.
- Added `/__tests__` for the Jest unit tests in `apps/frontend`, along with a `/components` folder containing a sample test component.
- Added dependencies required for unit testing in SpringBoot
- Added BackendSampleForTesting.java in "backend" folder and BackendSampleJUnitTest.java in "backendTests" folder

---

#### Frontend
1. Ensure that all packages are installed. ` npm i ` if it is not the case
2. Run `nx test frontend`

#### Backend
1. Select ` backend ` as root folder
2. Run ` mvn clean install ` 

---

### CODE REVIEW

**Comment by XavierGuertin** [comment]
Can you convert the PR has a draft if it's not ready yet please.

**Review by im-samwong — DISMISSED** [review]
Looks good.

**Review by LiamDaigle — DISMISSED** [review]
lgtm!

**Review by XavierGuertin — DISMISSED** [review]

**Review by LiamDaigle — APPROVED** [review]
lgtm!

**Review by im-samwong — APPROVED** [review]
LGTM

**Pull request merged**
