### PR TITLE
#4 - chore(documentation): Update Developer Getting Started Guide

### PR DESCRIPTION
**Pull request by PFratt**
### Summary
Made improvements to the "Developer Getting Started Guide"

### Changes Made
- Added steps to run the frontend

### CODE REVIEW

**Review by im-samwong — DISMISSED** [review]
LGTM

**Review by Fetyali7 — DISMISSED** [review]
Looks good to me!

**Review by im-samwong — APPROVED** [review]
LGTM

**Review by yasminehilout — APPROVED** [review]
Nice work Sam, it's clearer now!

**Pull request merged**
